---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/fedwrqmy/public_html/
    - /bin/cp -R * $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp ./build/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH 