---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/fedwrqmy/public_html/
    - /bin/rm -rf $DEPLOYPATH/*
    - /bin/cp -R build/* $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp build/_app/immutable/assets/app.css $DEPLOYPATH/app.css
    - /bin/cp build/_app/immutable/entry/start.js $DEPLOYPATH/start.js
    - /bin/cp build/_app/immutable/entry/app.js $DEPLOYPATH/app.js 